### PR TITLE
remove sentry ASGI middleware for fastapi, because it has auto fastapi integration

### PR DESCRIPTION
**Pull request by lesnik512**
More info about reasons here https://github.com/community-of-python/microbootstrap/pull/50

### CODE REVIEW

**Comment by vrslev** [comment]
I’d prefer to remote the instrument at all

**Comment by lesnik512** [comment]
> I’d prefer to remote the instrument at all

will it work?

**Comment by vrslev** [comment]
Well, you don’t do there anything anyway :)

**Comment by lesnik512** [comment]
> Well, you don’t do there anything anyway :)

I'm affraid, that without decorating with @FastApiBootstrapper.use_instrument() sentry bootstrap won't be used

**Comment by vrslev** [comment]
Hmm, I’m not sure

**Review by vrslev — APPROVED** [review]

**Pull request merged**
