### PR TITLE
Disable debug and reload & enable offline docs by default

### PR DESCRIPTION
**Pull request by vrslev**
The default behavior should work out of the box in production.

### CODE REVIEW

**Comment by insani7y** [comment]
Imo, but the default behaviour should be suitable for development :D.
Guess, it's some django vibes, but that's pretty much convenient

**Comment by vrslev** [comment]
My rationale is, that it is harder to shoot yourself in the foot when deploying services: you wouldn’t have to piece things together to figure out if the service is ready for production or not. 

A good example would be Uvicorn: it has `--reload` flag. Code reloading functionality is disabled by default so it’s explicit and you don’t need to think about it when deploying.

**Comment by vrslev** [comment]
I've moved enabling offline docs by default here from #20

**Comment by vrslev** [comment]
@xfenix said he'd be okay either way. I think if we prioritize development mode, we should list which settings should be disabled in production

**Comment by vrslev** [comment]
For services in my team it would be easier to make production mode the default

**Comment by insani7y** [comment]
It's actually not a big deal.   
We can try do like this and If someone won't be satisfied, we can change it back

**Review by insani7y — APPROVED** [review]

**Pull request merged**
